name = "Redsky Origins"
author = "Dorrel Redmond"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4fa5a3973d4bd69dfa47873871d7a7f41b5526cfd0eedbea66b5e4e57caead4"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
